version: "3.8"

services:
  db:
    image: postgres:16
    container_name: secure-db
    environment:
      POSTGRES_DB: SecureLoginDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ronil0905
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/SecureLoginDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ronil0905
      JWT_SECRET: yourSuperSecretKeyForPrimeTradeAssignment2026SecureJwtKey
      JWT_EXPIRATION: 86400000