# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/SecureLoginDB
spring.datasource.username=postgres
spring.datasource.password=ronil0905

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false