spring.datasource.url=jdbc:postgresql://localhost:5432/SecureLoginDB
spring.datasource.username=postgres
spring.datasource.password=ronil0905

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jwt.secret=yourSuperSecretKeyForPrimeTradeAssignment2026SecureJwtKey
jwt.expiration=86400000